### ISSUE TITLE
Setup redirection rules to ensure we keep same urls as in the previous documentation

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#117]
It seems that we have several use-cases that require it
- #24 
- #32 
- #34
- #55 if javadoc is hosted outside of the documentation site

As a first hosting solution, we chose GitHub Pages which doesn't allow to set custom redirect rules: https://docs.github.com/en/github/working-with-github-pages/getting-started-with-github-pages out of the box

**Comment by alachambre** [comment]
**Netlify experimentations summary**

Objectives: 

- Deploy a built version of the site on Netlify
- Validate that we can easily set up redirections rules to handle `bonita/latest` & `bonita/` use cases (same for all components)
- Ensure that domain name can be customised (i.e the url of the site has to be `documentation.bonitasoft.com/...`)

Results: 

I have been able to deploy a built version of the docsite easily using the [Netlify cli](https://docs.netlify.com/cli/get-started/). I followed the getting started so I created some extra configuration regarding the initial use case (build configuration), but it can be easily skipped. 

It can be summarised in a few steps: 

(https://docs.netlify.com/cli/get-started/) to install the netlify-cli, and to manage the tokens of your account locally
- Create a folder `test-netlify` containing the built docsite in a folder `site` and the following root configuration file: 

_netlify.toml_
```
[build]
  publish = "site"

[[redirects]]
  from = "/bonita/latest"
  to = "/bonita/7.12"

[[redirects]]
  from = "/bonita/"
  to = "/bonita/7.12"
```

- Run netlify deploy


-> Redirects are managed from the conf file, it works well. More details here.

Regarding the domain name, it seems to be quite easy to use a custom domain name for a site -> https://docs.netlify.com/domains-https/custom-domains/

Finally, about the pricing (https://www.netlify.com/pricing/): 
There is a free plan for `personal projects, hobby sites, or experiments`. This free plan could be enough, especially because we do not want to use their build infrastructure (w'll use github action and deploy the built site directly). 
The first paying option is 19$/month, the main difference for us is the bandwidth available: 100GB/month for the free plan to 400GB/month for the paying plan. 
I don't really know which one is the most interesting for us.

**Comment by tbouffard** [comment]
@alachambre very promising, nice
About the Netlify configuration file, we will have to check how/if we can integrate custom rules to what Antora can generate (https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/#generated-redirect-configuration-for-netlify). If this doesn't work, this is not a problem: we can keep the current configured behaviour which generates extra static refresh html pages (https://docs.antora.org/antora/2.3/playbook/urls-redirect-facility/#generated-static-html-refresh-pages) - not perfect but it does the trick!

**Comment by tbouffard** [comment]
Decisions on 2021-02-23: start deploying to netlify
See #130
Deployment url: https://documentation-bonita.netlify.app/
