### ISSUE TITLE
Replace black text with appropriate colors

### ISSUE THREAD

**Issue by LBALP** [bonitasoft/bonitasoft.github.io#121]
Replace the black text all over the website with this dark grey that we use for the corporate website already **#333333** and this blue **#19465F** for titles as on the corporate website 
![image](https://user-images.githubusercontent.com/52718045/108793149-bd07fb00-7537-11eb-87e0-93825af05c1f.png)

Follow the corporate website guidelines : 
![image](https://user-images.githubusercontent.com/52718045/108793432-618a3d00-7538-11eb-8634-520b5acfebc3.png)

**Comment by tbouffard** [comment]
@LBALP I guess you request this because you have in mind that the documentation site would/should perfectly match the Bonitasoft web design.
We don't have such requirements for now, and don't know if we want to follow it as this has maintenance implication (sync any design changes, who will manage it, ....). We will consider it later.

By the way, thanks for all the feedback you have provided, they will help us improving the site.

**Comment by LBALP** [comment]
@tbouffard I made all my design feedback as Nathalie asked me to help on that before the new website goes live. I talked to Adrien, he will implement the changes we agreed on ;)

Thanks team!
