### ISSUE TITLE
Tune the search trigger (debounce configuration)

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#148]
Currently, the search is triggered right after the letter is enter in the search box.
We should configure a debounce to launch the search after inactivity.
This will also avoid to have search statistics about one letter search which is useless and are the searches with the more occurrences.

**Comment by alachambre** [comment]
We can set following option: 
`searchAsYouType: true / false` (true by default) 

-> if false then the user has to press enter to trigger the search. 

It is not recommended by Algolia to introduce a debounce or a min number of char, and there is no documentation on how to do it with the docsearch UI. Actually, it is written in the documentation that when a user is writing, many requests are sent but Algolia only count one request (it matters for the paying plans). I guess it means that they are able know when several requests are part of the same request, and it is probably apply to the stats. 
We currently have many request for 'a', because I use this request a lot when I work on the UI. 

I suggest to do nothing for now, and see in a couple of weeks / months if it really impacts the stats or not.
