### ISSUE TITLE
Decide how we are going to manage document of component pre-versions

### ISSUE THREAD

**Issue by tbouffard** [bonitasoft/bonitasoft.github.io#35]
### What is a pre-version and how it is managed in the old doc site

- When development of a new version start, the documentation for this new version is initialized
It is publicly available but the version is not displayed in the version pick list.
- When the version is in beta, it is made available in the pick list (and displayed as beta) but is not selected by default, it is not the default version
- When the version is GA, update the default

Everything is managed in the documentation site generator project.

### To be decided

**Antora Default UI features**
- everything can be managed in the component documentation repsitory
- displayed version is configurable: https://docs.antora.org/antora/2.3/component-display-version/. So the documentation content repository can configured what has to be displayed (7.13 preview/dev, 7.13 beta, ....)
- prerelease version: https://docs.antora.org/antora/2.3/component-prerelease/. Prerelease are available in the pick list but not considered for the default/latest version computation

**Proposition 1: keep the existing behaviour**
Possible extension in Antora UI if we want to keep
in the `nav-explore.hbs`, the version list accesses to the component version elements. We could hide a prerelease version that has custom attributes/properties (if it can access to it, these elements can be configured in the antora config file in the component documentation repository) or if the displayed version contains a specific string (preview, dev).

**Proposition 2: switch to Antora default**
Is this really a problem to make the documentation of a preview/dev version visible to everybody.

**Comment by benjaminParisel** [comment]
We have decided to create a new branch [old_versions](https://github.com/bonitasoft/bonita-doc/blob/old_versions/antora.yml) bonita-doc repository.
A unique page is present to list the old archive version. We will add a link to download archive documentation as PDF (for drupal if we can) or static HTML bundle since 7.3.

At each release of Bonita we need to update this file to adding an "archived" version.

This mechanism allow us to follow and keep antora behabior.
